version: "3.8"

services:
  db:
    image: postgres:14-bullseye
    restart: always
    env_file:
      - ./.env
    expose:
      - 5432
    ports:
      - "5440:5432"
    volumes:
      - ./sqls/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./sqls/user_tables.sql:/docker-entrypoint-initdb.d/user_tables.sql
      - ./postgres_data:/var/lib/postgresql/data/

  app:
    build: ./
    restart: always
    command: sh -c "uvicorn main:app --host=0.0.0.0 --port 8000 --reload"
    working_dir: /app
    env_file:
      - ./.env
    volumes:
      - ./:/app:cached
    expose:
      - 8000
    ports:
      - "8001:8000"
    depends_on:
      - db
